-- ORDENA SPACE
-- Schema Oracle para Tomcat 10 + Jakarta Servlet/JSP + JDBC

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE servicos_ativos CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE setor_pontos_gps CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE setores CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE policiais CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE viaturas CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE usuarios CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(150 CHAR) NOT NULL,
    senha_hash VARCHAR2(64 CHAR) NOT NULL,
    perfil VARCHAR2(20 CHAR) NOT NULL,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT ck_usuarios_perfil CHECK (perfil IN ('ADMIN'))
);

CREATE TABLE viaturas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR2(20 CHAR) NOT NULL,
    placa VARCHAR2(10 CHAR) NOT NULL,
    tablet_satelital VARCHAR2(20 CHAR) NOT NULL,
    CONSTRAINT uk_viaturas_numero UNIQUE (numero),
    CONSTRAINT uk_viaturas_placa UNIQUE (placa),
    CONSTRAINT uk_viaturas_tablet UNIQUE (tablet_satelital)
);

CREATE TABLE policiais (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rg VARCHAR2(20 CHAR) NOT NULL,
    graduacao VARCHAR2(30 CHAR) NOT NULL,
    nome_guerra VARCHAR2(100 CHAR) NOT NULL,
    CONSTRAINT uk_policiais_rg UNIQUE (rg),
    CONSTRAINT ck_policiais_graduacao CHECK (graduacao IN ('Soldado', 'Cabo', 'Sargento'))
);

CREATE TABLE setores (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100 CHAR) NOT NULL,
    CONSTRAINT uk_setores_nome UNIQUE (nome)
);

CREATE TABLE setor_pontos_gps (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setor_id NUMBER NOT NULL,
    ordem_ponto NUMBER(1) NOT NULL,
    latitude NUMBER(10, 6) NOT NULL,
    longitude NUMBER(10, 6) NOT NULL,
    CONSTRAINT fk_setor_pontos_setor FOREIGN KEY (setor_id) REFERENCES setores (id) ON DELETE CASCADE,
    CONSTRAINT uk_setor_pontos_ordem UNIQUE (setor_id, ordem_ponto),
    CONSTRAINT ck_setor_pontos_ordem CHECK (ordem_ponto BETWEEN 1 AND 6)
);

CREATE TABLE servicos_ativos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viatura_id NUMBER NOT NULL,
    setor_id NUMBER NOT NULL,
    policial_1_id NUMBER NOT NULL,
    policial_2_id NUMBER NULL,
    data_hora_inicio TIMESTAMP NOT NULL,
    duracao_horas NUMBER(2) DEFAULT 12 NOT NULL,
    status VARCHAR2(20 CHAR) NOT NULL,
    latitude_atual NUMBER(10, 6) NULL,
    longitude_atual NUMBER(10, 6) NULL,
    CONSTRAINT fk_servicos_viatura FOREIGN KEY (viatura_id) REFERENCES viaturas (id),
    CONSTRAINT fk_servicos_setor FOREIGN KEY (setor_id) REFERENCES setores (id),
    CONSTRAINT fk_servicos_policial_1 FOREIGN KEY (policial_1_id) REFERENCES policiais (id),
    CONSTRAINT fk_servicos_policial_2 FOREIGN KEY (policial_2_id) REFERENCES policiais (id),
    CONSTRAINT ck_servicos_status CHECK (status IN ('AGUARDANDO_GPS', 'NORMAL', 'ALERTA', 'FINALIZADO')),
    CONSTRAINT ck_servicos_duracao CHECK (duracao_horas > 0),
    CONSTRAINT ck_servicos_policiais_distintos CHECK (policial_2_id IS NULL OR policial_1_id <> policial_2_id)
);
